### ISSUE TITLE
`unit="eV"` or `units="eV"`

### ISSUE THREAD

**Issue by samwaseda** [pyiron/semantikon#30]
Today I realized that Simon Stier was using `unit` in his data class, which was also the case in atomRDF. But I have to say it feels a lot more natural to me to write `u(float, units="eV")` than `u(float, unit="eV")`, which is also the reason why it's `units` in `semantikon`, although I cannot really explain why. Is it only me and should I change it to `unit`? @liamhuber @Tara-Lakshmipathy @srmnitc

**Comment by Tara-Lakshmipathy** [comment]
To be frank, I'm used to calling it `units` as well and `unit` sounds strange to me. But I guess according to [Oxford dictionary](https://www.oxfordreference.com/display/10.1093/oi/authority.20110803110720761), unit is the correct term when dealing with a single quantity.

**Comment by liamhuber** [comment]
Unnamed ensign: commander, there is a Klingon bird of prey 30 to starboard!

Cmdr Riker: 30 what?! Dammit ensign, give me the units!



All I can say is that it would feel really weird to me if Riker said "unit" there.

**Comment by liamhuber** [comment]
A thalli, it's probably because we pluralize almost all our unit uses, eg "3m" is "three meters", not "three meter". The only time we use the singular is when we have _exactly_ one of something, which just for statistical reasons doesn't come up much and wouldn't usually be casually assumed. "_x_ m" is "_x_ meters" and you'd say "what are the units of _x_", even though it has _a unit_ variable associated with it... I think

**Comment by samwaseda** [comment]
Actually I'm not so concerned whether it is linguistically correct (probably I should, though), but I thought I was offering something that was obviously wrong. So thanks for your replies. I'm gonna leave it like this then.
